### ISSUE TITLE
I couldn't use the Hector Quadrotor to control the UAV?

### ISSUE THREAD

**Issue by lijoe123** [RAFALAMAO/hector-quadrotor-noetic#10]
Hello! I had follow the step to run the command, but i can't use the Hector Quadrotor to control the UAV.
![图片](https://user-images.githubusercontent.com/86214036/197664975-1d7c3492-6ae8-47dc-9b3a-baca15ae03d8.png)
Thank you!!!!!

**Comment by RAFALAMAO** [comment]
Did you try with "up" button?, "take off" doesn't works.

It's like if UI isn't suscribed to hector's topics, you should see if hector is publishing apropiated topics.

**Comment by lijoe123** [comment]
Thank you for your answer. I fix this problem by run the command `catkin_make`, I hope you can add it to your md.
By the way, Could you please tell me how to connect the px4 with hector_quadrotor
