### ISSUE TITLE
hector_quadrotor hovering while using teleop_twist_keyboard

### ISSUE THREAD

**Issue by sandilyasg** [RAFALAMAO/hector-quadrotor-noetic#11]
How did you get hector_quadrotor to hover while using teleop_twist_keyboard? As in what code did you have to change to allow this, because in the [melodic version](https://github.com/tu-darmstadt-ros-pkg/hector_quadrotor) when you use teleop_twist_keyboard and hit 't' to gain altitude, once you let go, it comes back down to the ground. I understand this is because there are no commands being sent to keep it at that level, so I was wondering what code do I need to change in the melodic version to enable this. @RAFALAMAO

**Comment by RAFALAMAO** [comment]
Sorry my late response xc.

But bro, when you click "k" it stays in same z position o.o

Or what do you want to do?

**Comment by sandilyasg** [comment]
@RAFALAMAO thanks for replying! I was wondering if you changed any control code in this noetic version when you ported it from ROS melodic. If I click "k" in the ROS melodic version would it still stay in the same z position?

**Comment by RAFALAMAO** [comment]
Damn, I dont know man, because I never used melodic version xc

And I don't remember have changed something about hover functionality
