### ISSUE TITLE
Invalid Param error while roslaunch hector_quadrotor_gazebo quadrotor_empty_world.launch

### ISSUE THREAD

**Issue by sumedhreddy90** [RAFALAMAO/hector-quadrotor-noetic#2]
Invalid <param> tag: Cannot load command parameter [robot_description]: command [['/opt/ros/noetic/lib/xacro/xacro', '/home/starfleeet-robotics/catkin_ws/src/hector_quadrotor_noetic/hector_quadrotor/hector_quadrotor_description/urdf/quadrotor.gazebo.xacro', 'base_link_frame:=/base_link', 'world_frame:=world']] returned with code [2]. 

Param xml is <param name="robot_description" command="$(find xacro)/xacro '$(arg model)' base_link_frame:=$(arg base_link_frame) world_frame:=$(arg world_frame)"/>

**Comment by sumedhreddy90** [comment]
aram xml is <param name="robot_description" command="$(find xacro)/xacro '$(arg model)' base_link_frame:=$(arg base_link_frame) world_frame:=$(arg world_frame)"/>

**Comment by sumedhreddy90** [comment]
aram xml is <param name="robot_description" command="$(find xacro)/xacro '$(arg model)' base_link_frame:=$(arg base_link_frame) world_frame:=$(arg world_frame)"/>

**Comment by RAFALAMAO** [comment]
Sorry, I didn't understood the issue, if you explain me in more details.

**Comment by Fatimah-Alahmed** [comment]
I had the same problem when I run roslaunch, so I have changed command in the <param> tag to default, this solved the problem. Then, I tried changing to default to textfile However, I encounter another problem which says that it can not find the file and also give me traceback for files in the opt/ros/noetic/lib/python3/dist-packages/ (some python files). Do you know what is the problem? 

The first error before changing the command:
redefining global symbol: pi
when processing file: /home/parallels/catkin_ws/src/hector_quadrotor_noetic/hector_quadrotor/hector_quadrotor_description/urdf/quadrotor_base.urdf.xacro
included from: /home/parallels/catkin_ws/src/hector_quadrotor_noetic/hector_quadrotor/hector_quadrotor_description/urdf/quadrotor.urdf.xacro
included from: /home/parallels/catkin_ws/src/hector_quadrotor_noetic/hector_quadrotor/hector_quadrotor_description/urdf/quadrotor.gazebo.xacro
No such file or directory: /home/parallels/catkin_ws/src/hector_quadrotor_noetic/hector_quadrotor/hector_quadrotor_gazebo/urdf/quadrotor_plugins.gazebo.xacro [Errno 2] No such file or directory: '/home/parallels/catkin_ws/src/hector_quadrotor_noetic/hector_quadrotor/hector_quadrotor_gazebo/urdf/quadrotor_plugins.gazebo.xacro'
when processing file: /home/parallels/catkin_ws/src/hector_quadrotor_noetic/hector_quadrotor/hector_quadrotor_description/urdf/quadrotor.gazebo.xacro
RLException: while processing /home/parallels/catkin_ws/src/hector_quadrotor_noetic/hector_quadrotor/hector_quadrotor_gazebo/launch/spawn_quadrotor.launch:
Invalid <param> tag: Cannot load command parameter [robot_description]: command [['/opt/ros/noetic/lib/xacro/xacro', '/home/parallels/catkin_ws/src/hector_quadrotor_noetic/hector_quadrotor/hector_quadrotor_description/urdf/quadrotor.gazebo.xacro', 'base_link_frame:=/base_link', 'world_frame:=world']] returned with code [2].

Param xml is <param name="robot_description" command="$(find xacro)/xacro '$(arg model)' base_link_frame:=$(arg base_link_frame) world_frame:=$(arg world_frame)"/>
The traceback for the exception was written to the log file

The error after changing command to default:

.. logging to /home/parallels/.ros/log/414eeecc-5620-11ec-9974-33e66f355017/roslaunch-ubuntu-linux-20-04-desktop-78810.log
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

RLException: while processing /home/parallels/catkin_ws/src/hector_quadrotor_noetic/hector_quadrotor/hector_quadrotor_gazebo/launch/spawn_quadrotor.launch:
<param> tag must have one and only one of value/textfile/binfile.
The traceback for the exception was written to the log file

**Comment by RAFALAMAO** [comment]
Which roslaunch terminal command are you using?

**Comment by Fatimah-Alahmed** [comment]
roslaunch hector_quadrotor_gazebo quadrotor_empty_world.launch 
 or even 
roslaunch hector_quadrotor_demo outdoor_flight_gazebo.launch

**Comment by RAFALAMAO** [comment]
Sorry, but I don't know why it¿s happening :/, may be, just may be... the workspace folder name, mine is "catking_ws".

Here is a video of demonstration:

https://www.youtube.com/watch?v=-2IWfZjqoNc

**Comment by RAFALAMAO** [comment]
May you attach a Image with console error, please?

**Comment by Fatimah-Alahmed** [comment]
<img width="1147" alt="Screen Shot 1443-05-16 at 6 58 03 PM" src="https://user-images.githubusercontent.com/63425641/146796424-a2b0fa92-e8dd-43af-8dbb-d175ae74bf98.png">

**Comment by Fatimah-Alahmed** [comment]
I have tried to add a file(Quadrotor_plugins.gazebo.xacro), the result is that now gazebo opens with the drone. but when I try to operate it using( rosrun teleop_twist_keyboard teleop_twist_keyboard.py )
 it is not running. 
However, there is an error when using (roslaunch hector_quadrotor_gazebo quadrotor_empty_world.launch)
<img width="1147" alt="Screen Shot 1443-05-16 at 7 13 02 PM" src="https://user-images.githubusercontent.com/63425641/146798305-713b0595-77fe-4eec-8681-b662ad459ada.png">

**Comment by RAFALAMAO** [comment]
Where did you clone and compile de package, "path"?

**Comment by Juann-SPS** [comment]
I have the same error thats happening in the first image, do you have any idea of what could be making such an error or how it could be trespassed/solved?
