### ISSUE TITLE
Roslaunch is not working

### ISSUE THREAD

**Issue by Fatimah-Alahmed** [RAFALAMAO/hector-quadrotor-noetic#3]
I had a problem when I run roslaunch, so I have changed command in the tag to default, this solved the problem. Then, I tried changing to default to textfile However, I encounter another problem which says that it can not find the file and also give me traceback for files in the opt/ros/noetic/lib/python3/dist-packages/ (some python files). Do you know what is the problem?

The first error before changing the command:
redefining global symbol: pi
when processing file: /home/parallels/catkin_ws/src/hector_quadrotor_noetic/hector_quadrotor/hector_quadrotor_description/urdf/quadrotor_base.urdf.xacro
included from: /home/parallels/catkin_ws/src/hector_quadrotor_noetic/hector_quadrotor/hector_quadrotor_description/urdf/quadrotor.urdf.xacro
included from: /home/parallels/catkin_ws/src/hector_quadrotor_noetic/hector_quadrotor/hector_quadrotor_description/urdf/quadrotor.gazebo.xacro
No such file or directory: /home/parallels/catkin_ws/src/hector_quadrotor_noetic/hector_quadrotor/hector_quadrotor_gazebo/urdf/quadrotor_plugins.gazebo.xacro [Errno 2] No such file or directory: '/home/parallels/catkin_ws/src/hector_quadrotor_noetic/hector_quadrotor/hector_quadrotor_gazebo/urdf/quadrotor_plugins.gazebo.xacro'
when processing file: /home/parallels/catkin_ws/src/hector_quadrotor_noetic/hector_quadrotor/hector_quadrotor_description/urdf/quadrotor.gazebo.xacro
RLException: while processing /home/parallels/catkin_ws/src/hector_quadrotor_noetic/hector_quadrotor/hector_quadrotor_gazebo/launch/spawn_quadrotor.launch:
Invalid tag: Cannot load command parameter [robot_description]: command [['/opt/ros/noetic/lib/xacro/xacro', '/home/parallels/catkin_ws/src/hector_quadrotor_noetic/hector_quadrotor/hector_quadrotor_description/urdf/quadrotor.gazebo.xacro', 'base_link_frame:=/base_link', 'world_frame:=world']] returned with code [2].

Param xml is
The traceback for the exception was written to the log file

The error after changing command to default:

.. logging to /home/parallels/.ros/log/414eeecc-5620-11ec-9974-33e66f355017/roslaunch-ubuntu-linux-20-04-desktop-78810.log
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

RLException: while processing /home/parallels/catkin_ws/src/hector_quadrotor_noetic/hector_quadrotor/hector_quadrotor_gazebo/launch/spawn_quadrotor.launch:

tag must have one and only one of value/textfile/binfile. The traceback for the exception was written to the log file

**Comment by Fatimah-Alahmed** [comment]
roslaunch hector_quadrotor_gazebo quadrotor_empty_world.launch

**Comment by RAFALAMAO** [comment]
Same issue, just in one thread.
