### ISSUE TITLE
Error loading some assets

### ISSUE THREAD

**Issue by niniack** [RAFALAMAO/hector-quadrotor-noetic#4]
Hi, 

I'm using this quadrotor model with the Neurorobotics Platform, which as far as I know is basically just ROS + spiking neural network librar(y/ies) + custom UI

I was given [these instructions](https://forum.humanbrainproject.eu/t/uploading-custom-robots-models/1710/8) by the team and I was able to get through them. However, upon launching the simulation their platform gives me the error:

```
Error while loading some assets!

quadrotor::base_link::base_link_fixed_joint_lump__sonar_link_visual_1
quadrotor::base_link::base_link_visual

Some assets have not been found!
```

While I understand you may be unfamiliar with the NRP, would you happen to know what could cause this error?

Thanks!

**Comment by RAFALAMAO** [comment]
Sorry my friend, I have not idea how it works xc
