### ISSUE TITLE
Protocol Buffer Error in Arch Linux

### ISSUE THREAD

**Issue by kanishkanarch** [RAFALAMAO/hector-quadrotor-noetic#5]
On building the hector drone package, I am encountering the following Protobuf error:

[error.txt](https://github.com/RAFALAMAO/hector-quadrotor-noetic/files/8802715/error.txt)
![image](https://user-images.githubusercontent.com/52484751/171110603-9fb4c1f0-47fa-4c12-b8d9-b5646a3731fc.png)

I encountered the same error in multiple other projects, like [this issue in PXLRoboticsLab's ardrone repo](https://github.com/PXLRoboticsLab/ardrone_gazebo/issues/1).

Kindly help me solve this version issue.

Some outputs that might be helpful:

1. `protoc --version` results in version `libprotoc 3.20.1`
2. `which protoc` results in location `/usr/bin/protoc`
3. `/usr/bin/protoc --version` results in version `libprotoc 3.20.1`

**Comment by RAFALAMAO** [comment]
You may try this https://github.com/BVLC/caffe/issues/6527#:~:text=about%20this%20project%3F-,This%20file%20was%20generated%20by%20an%20older%20version%20of%20protoc,a%20newer%20version%20of%20protoc.

**Comment by computational-physcis-2011301020083** [comment]
sudo apt-get remove protobuf-compiler
python -m pip install protobuf==3.6.1
